### ISSUE TITLE
C++ auto-completion doesn't work with R 4.0.0

### ISSUE THREAD

**Issue by kevinushey** [rstudio/rstudio#6977]
### System details

    RStudio Edition : Desktop
    RStudio Version : v1.3.957
    OS Version      : macOS 10.15.4
    R Version       : 4.0.0

### Steps to reproduce the problem

Given this document, with `|` representing the cursor position:

```
#include <vector>

void test() {
  std::vector<int> x;
  x.|
}
```

Save this as a C++ file (e.g. `test.cpp`), and then try to press Tab to request completions.

### Describe the problem in detail

No completions are displayed.

### Describe the behavior you expected

Completions should be displayed.

### Notes

Output with `.rs.setClangDiagnostics(2)`:

```
CLANG INDEXING: /Users/kevinushey/scratch/test.cpp
CLANG REMOVE INDEX: /Users/kevinushey/scratch/test.cpp
COMPILATION ARGUMENTS:
[
    "-isystem",
    "/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include",
    "-I/Library/Developer/CommandLineTools/usr/lib/clang/11.0.0/include",
    "-I/Library/Developer/CommandLineTools/usr/bin/../include/c++/v1",
    "-I/Library/Developer/CommandLineTools/usr/lib/clang/11.0.0/include",
    "-I/Library/Developer/CommandLineTools/usr/include",
    "-I/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include",
    "-std=gnu++11",
    "-I/Library/Frameworks/R.framework/Resources/include",
    "-DNDEBUG",
    "-I/Users/kevinushey/Library/R/4.0/library/Rcpp/include",
    "-I/Users/kevinushey/scratch",
    "-I/usr/local/include",
    "-fPIC",
    "-include-pch",
    "/tmp/RtmpVEfzoq/rstudio/libclang/precompiled/Rcpp/67CB9813/1.0.4.6-x86_64-apple-darwin17.0-78286-11.0.0/Rcpp-std=gnu++11.pch",
    "-v"
]
  (Creating new index)
Apple clang version 11.0.0 (clang-1100.0.33.8)
Target: x86_64-apple-darwin19.4.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin
ignoring nonexistent directory "/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/c++/v1"
ignoring nonexistent directory "/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/local/include"
ignoring nonexistent directory "/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/Library/Frameworks"
ignoring duplicate directory "/Library/Developer/CommandLineTools/usr/lib/clang/11.0.0/include"
ignoring duplicate directory "/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include"
  as it is a non-system directory that duplicates a system directory
ignoring duplicate directory "/Library/Developer/CommandLineTools/usr/bin/../include/c++/v1"
  as it is a non-system directory that duplicates a system directory
ignoring duplicate directory "/Library/Developer/CommandLineTools/usr/lib/clang/11.0.0/include"
  as it is a non-system directory that duplicates a system directory
ignoring duplicate directory "/Library/Developer/CommandLineTools/usr/include"
  as it is a non-system directory that duplicates a system directory
ignoring duplicate directory "/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include"
#include "..." search starts here:
#include <...> search starts here:
 /Library/Frameworks/R.framework/Resources/include
 /Users/kevinushey/Library/R/4.0/library/Rcpp/include
 /Users/kevinushey/scratch
 /usr/local/include
 /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include
 /Library/Developer/CommandLineTools/usr/bin/../include/c++/v1
 /Library/Developer/CommandLineTools/usr/lib/clang/11.0.0/include
 /Library/Developer/CommandLineTools/usr/include
 /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/System/Library/Frameworks (framework directory)
End of search list.
/Library/Developer/CommandLineTools/usr/bin/../include/c++/v1/vector:339:38: error: no type named 'const_pointer' in 'std::__1::allocator_traits<std::__1::allocator<int> >'
/Library/Developer/CommandLineTools/usr/bin/../include/c++/v1/vector:471:15: note: in instantiation of template class 'std::__1::__vector_base<int, std::__1::allocator<int> >' requested here
/Users/kevinushey/scratch/test.cpp:7:20: note: in instantiation of template class 'std::__1::vector<int, std::__1::allocator<int> >' requested here
/Library/Developer/CommandLineTools/usr/bin/../include/c++/v1/memory:2220:38: error: no member named 'value' in 'std::__1::is_same<int, std::__1::allocator<int> >'
/Library/Developer/CommandLineTools/usr/bin/../include/c++/v1/vector:345:48: note: in instantiation of template class 'std::__1::__compressed_pair<int, std::__1::allocator<int> >' requested here
/Library/Developer/CommandLineTools/usr/bin/../include/c++/v1/vector:471:15: note: in instantiation of template class 'std::__1::__vector_base<int, std::__1::allocator<int> >' requested here
/Users/kevinushey/scratch/test.cpp:7:20: note: in instantiation of template class 'std::__1::vector<int, std::__1::allocator<int> >' requested here
/Library/Developer/CommandLineTools/usr/bin/../include/c++/v1/vector:481:30: error: 'reference' is a protected member of 'std::__1::__vector_base<int, std::__1::allocator<int> >'
/Users/kevinushey/scratch/test.cpp:7:20: note: in instantiation of template class 'std::__1::vector<int, std::__1::allocator<int> >' requested here
/Library/Developer/CommandLineTools/usr/bin/../include/c++/v1/vector:335:54: note: declared protected here
/Library/Developer/CommandLineTools/usr/bin/../include/c++/v1/vector:482:30: error: 'const_reference' is a protected member of 'std::__1::__vector_base<int, std::__1::allocator<int> >'
/Library/Developer/CommandLineTools/usr/bin/../include/c++/v1/vector:336:54: note: declared protected here
/Library/Developer/CommandLineTools/usr/bin/../include/c++/v1/vector:484:30: error: 'difference_type' is a protected member of 'std::__1::__vector_base<int, std::__1::allocator<int> >'
/Library/Developer/CommandLineTools/usr/bin/../include/c++/v1/vector:337:54: note: declared protected here
/Library/Developer/CommandLineTools/usr/bin/../include/c++/v1/vector:485:30: error: 'pointer' is a protected member of 'std::__1::__vector_base<int, std::__1::allocator<int> >'
/Library/Developer/CommandLineTools/usr/bin/../include/c++/v1/vector:338:54: note: declared protected here
/Library/Developer/CommandLineTools/usr/bin/../include/c++/v1/vector:486:30: error: 'const_pointer' is a protected member of 'std::__1::__vector_base<int, std::__1::allocator<int> >'
/Library/Developer/CommandLineTools/usr/bin/../include/c++/v1/vector:339:54: note: declared protected here
/Library/Developer/CommandLineTools/usr/bin/../include/c++/v1/vector:492:78: error: no member named 'value' in 'std::__1::is_same<int, int>'
TOTAL MEMORY: 27 mb (test.cpp)
PERFORMANCE 22 ms (test.cpp)
```

The attempt to force the use of system headers seems to break things with Apple clang.

---

- [x] I have read the guide to submitting good bug reports at https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports . 
- [x] I have installed the latest version of RStudio and confirmed that the issue still persists.
- [x] If I am reporting a RStudio crash, I have included a diagnostics report. https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by dfalty** [comment]
Hey @kevinushey, I can't get this to work on my Mac 10.15.2 with R 4.0.1 and RStudio version 1.3.1033. Did this make it into the patch build? 

Note: It works fine if I downgrade to R 3.6.3

**Comment by kevinushey** [comment]
Strange -- it works fine for me, and the associated PR did indeed make it into the patch build:

https://github.com/rstudio/rstudio/commit/b1082b045c705fefe64ee91187d87e98ef258cf5

For the scenario that doesn't work, can you try running:

```
.rs.setClangDiagnostics(2)
```

and share the output in the console that's emitted when you try to request completions?

**Comment by randy3k** [comment]
Does it fix https://github.com/rstudio/rstudio/issues/4685#issuecomment-633316768?

**Comment by dfalty** [comment]
@kevinushey Here you go. Looks like this doesn't work for me on 1.3.1045 as well.

```
.rs.setClangDiagnostics(2)
Attemping to load libclang for x86_64-apple-darwin17.0 
/Applications/RStudio.app/Contents/MacOS/rsclang/libclang.dylib
   (Not Found)
/Library/Developer/CommandLineTools/usr/lib/libclang.dylib
   LOADED: 11.0.0

Restarting R session...

CLANG INDEXING: /Users/darbyhadley/asf2323/things.cpp
GENERATING PRECOMPILED HEADERS:
[
    "-I/Library/Developer/CommandLineTools/usr/lib/clang/11.0.0/include",
    "-I/usr/local/include",
    "-I/Library/Developer/CommandLineTools/usr/bin/../include/c++/v1",
    "-I/Library/Developer/CommandLineTools/usr/lib/clang/11.0.0/include",
    "-I/Library/Developer/CommandLineTools/usr/include",
    "-I/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include",
    "-I/Library/Frameworks/R.framework/Resources/include",
    "-DNDEBUG",
    "-I/Library/Frameworks/R.framework/Versions/4.0/Resources/library/Rcpp/include",
    "-I/Users/darbyhadley/asf2323",
    "-I/usr/local/include",
    "-fPIC",
    "-I/Library/Frameworks/R.framework/Versions/4.0/Resources/library/Rcpp/include",
    "-std=gnu++11"
]
/Library/Developer/CommandLineTools/usr/bin/../include/c++/v1/cmath:314:9: error: no member named 'signbit' in the global namespace
/Library/Developer/CommandLineTools/usr/bin/../include/c++/v1/cmath:315:9: error: no member named 'fpclassify' in the global namespace
/Library/Developer/CommandLineTools/usr/bin/../include/c++/v1/cmath:316:9: error: no member named 'isfinite' in the global namespace
/Library/Developer/CommandLineTools/usr/bin/../include/c++/v1/cmath:317:9: error: no member named 'isinf' in the global namespace
/Library/Developer/CommandLineTools/usr/bin/../include/c++/v1/cmath:318:9: error: no member named 'isnan' in the global namespace
/Library/Developer/CommandLineTools/usr/bin/../include/c++/v1/cmath:319:9: error: no member named 'isnormal' in the global namespace
/Library/Developer/CommandLineTools/usr/bin/../include/c++/v1/cmath:320:9: error: no member named 'isgreater' in the global namespace
/Library/Developer/CommandLineTools/usr/bin/../include/c++/v1/cmath:321:9: error: no member named 'isgreaterequal' in the global namespace
/Library/Developer/CommandLineTools/usr/bin/../include/c++/v1/cmath:322:9: error: no member named 'isless' in the global namespace
/Library/Developer/CommandLineTools/usr/bin/../include/c++/v1/cmath:323:9: error: no member named 'islessequal' in the global namespace
/Library/Developer/CommandLineTools/usr/bin/../include/c++/v1/cmath:324:9: error: no member named 'islessgreater' in the global namespace
/Library/Developer/CommandLineTools/usr/bin/../include/c++/v1/cmath:325:9: error: no member named 'isunordered' in the global namespace
/Library/Developer/CommandLineTools/usr/bin/../include/c++/v1/cmath:326:9: error: no member named 'isunordered' in the global namespace
/Library/Developer/CommandLineTools/usr/bin/../include/c++/v1/cmath:332:9: error: no member named 'abs' in the global namespace
/Library/Developer/CommandLineTools/usr/bin/../include/c++/v1/cmath:552:28: error: expected a qualified name after 'typename'
/Library/Developer/CommandLineTools/usr/bin/../include/c++/v1/cmath:552:37: error: expected ';' at end of declaration
/Library/Developer/CommandLineTools/usr/bin/../include/c++/v1/cmath:552:37: error: expected unqualified-id
/Library/Developer/CommandLineTools/usr/bin/../include/c++/v1/cmath:564:39: error: use of undeclared identifier 'is_floating_point'
/Library/Developer/CommandLineTools/usr/bin/../include/c++/v1/cmath:564:57: error: '_A1' does not refer to a value
/Library/Developer/CommandLineTools/usr/bin/../include/c++/v1/cmath:562:17: note: declared here
fatal error: too many errors emitted, stopping now [-ferror-limit=]
COMPILATION ARGUMENTS:
[
    "-I/Library/Developer/CommandLineTools/usr/lib/clang/11.0.0/include",
    "-I/usr/local/include",
    "-I/Library/Developer/CommandLineTools/usr/bin/../include/c++/v1",
    "-I/Library/Developer/CommandLineTools/usr/lib/clang/11.0.0/include",
    "-I/Library/Developer/CommandLineTools/usr/include",
    "-I/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include",
    "-std=gnu++11",
    "-I/Library/Frameworks/R.framework/Resources/include",
    "-DNDEBUG",
    "-I/Library/Frameworks/R.framework/Versions/4.0/Resources/library/Rcpp/include",
    "-I/Users/darbyhadley/asf2323",
    "-I/usr/local/include",
    "-fPIC",
    "-include-pch",
    "/var/folders/tg/12vm8qdj2l592vg5f9w2ljfh0000gn/T/Rtmp4j56Yp/rstudio/libclang/precompiled/Rcpp/CEDFA90F/1.0.4.6-x86_64-apple-darwin17.0-78648-11.0.0/Rcpp-std=gnu++11.pch",
    "-v"
]
  (Creating new index)
Apple clang version 11.0.0 (clang-1100.0.33.8)
Target: x86_64-apple-darwin19.2.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin
ignoring nonexistent directory "/usr/include/c++/v1"
ignoring nonexistent directory "/usr/include"
ignoring duplicate directory "/Library/Developer/CommandLineTools/usr/lib/clang/11.0.0/include"
ignoring duplicate directory "/usr/local/include"
ignoring duplicate directory "/Library/Developer/CommandLineTools/usr/bin/../include/c++/v1"
  as it is a non-system directory that duplicates a system directory
ignoring duplicate directory "/usr/local/include"
  as it is a non-system directory that duplicates a system directory
ignoring duplicate directory "/Library/Developer/CommandLineTools/usr/lib/clang/11.0.0/include"
  as it is a non-system directory that duplicates a system directory
ignoring duplicate directory "/Library/Developer/CommandLineTools/usr/include"
  as it is a non-system directory that duplicates a system directory
#include "..." search starts here:
#include <...> search starts here:
 /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include
 /Library/Frameworks/R.framework/Resources/include
 /Library/Frameworks/R.framework/Versions/4.0/Resources/library/Rcpp/include
 /Users/darbyhadley/asf2323
 /Library/Developer/CommandLineTools/usr/bin/../include/c++/v1
 /usr/local/include
 /Library/Developer/CommandLineTools/usr/lib/clang/11.0.0/include
 /Library/Developer/CommandLineTools/usr/include
 /System/Library/Frameworks (framework directory)
 /Library/Frameworks (framework directory)
End of search list.
/Library/Developer/CommandLineTools/usr/bin/../include/c++/v1/vector:339:38: error: no type named 'const_pointer' in 'std::__1::allocator_traits<std::__1::allocator<int> >'
/Library/Developer/CommandLineTools/usr/bin/../include/c++/v1/vector:471:15: note: in instantiation of template class 'std::__1::__vector_base<int, std::__1::allocator<int> >' requested here
/Users/darbyhadley/asf2323/things.cpp:4:20: note: in instantiation of template class 'std::__1::vector<int, std::__1::allocator<int> >' requested here
/Library/Developer/CommandLineTools/usr/bin/../include/c++/v1/memory:2220:38: error: no member named 'value' in 'std::__1::is_same<int, std::__1::allocator<int> >'
/Library/Developer/CommandLineTools/usr/bin/../include/c++/v1/vector:345:48: note: in instantiation of template class 'std::__1::__compressed_pair<int, std::__1::allocator<int> >' requested here
/Library/Developer/CommandLineTools/usr/bin/../include/c++/v1/vector:471:15: note: in instantiation of template class 'std::__1::__vector_base<int, std::__1::allocator<int> >' requested here
/Users/darbyhadley/asf2323/things.cpp:4:20: note: in instantiation of template class 'std::__1::vector<int, std::__1::allocator<int> >' requested here
/Library/Developer/CommandLineTools/usr/bin/../include/c++/v1/vector:481:30: error: 'reference' is a protected member of 'std::__1::__vector_base<int, std::__1::allocator<int> >'
/Users/darbyhadley/asf2323/things.cpp:4:20: note: in instantiation of template class 'std::__1::vector<int, std::__1::allocator<int> >' requested here
/Library/Developer/CommandLineTools/usr/bin/../include/c++/v1/vector:335:54: note: declared protected here
/Library/Developer/CommandLineTools/usr/bin/../include/c++/v1/vector:482:30: error: 'const_reference' is a protected member of 'std::__1::__vector_base<int, std::__1::allocator<int> >'
/Library/Developer/CommandLineTools/usr/bin/../include/c++/v1/vector:336:54: note: declared protected here
/Library/Developer/CommandLineTools/usr/bin/../include/c++/v1/vector:484:30: error: 'difference_type' is a protected member of 'std::__1::__vector_base<int, std::__1::allocator<int> >'
/Library/Developer/CommandLineTools/usr/bin/../include/c++/v1/vector:337:54: note: declared protected here
/Library/Developer/CommandLineTools/usr/bin/../include/c++/v1/vector:485:30: error: 'pointer' is a protected member of 'std::__1::__vector_base<int, std::__1::allocator<int> >'
/Library/Developer/CommandLineTools/usr/bin/../include/c++/v1/vector:338:54: note: declared protected here
/Library/Developer/CommandLineTools/usr/bin/../include/c++/v1/vector:486:30: error: 'const_pointer' is a protected member of 'std::__1::__vector_base<int, std::__1::allocator<int> >'
/Library/Developer/CommandLineTools/usr/bin/../include/c++/v1/vector:339:54: note: declared protected here
/Library/Developer/CommandLineTools/usr/bin/../include/c++/v1/vector:492:78: error: no member named 'value' in 'std::__1::is_same<int, int>'
/Users/darbyhadley/asf2323/things.cpp:6:1: error: expected unqualified-id
TOTAL MEMORY: 27 mb (things.cpp)
PERFORMANCE 2038 ms (things.cpp)
ignoring nonexistent directory "/usr/include/c++/v1"
ignoring nonexistent directory "/usr/include"
ignoring duplicate directory "/Library/Developer/CommandLineTools/usr/lib/clang/11.0.0/include"
ignoring duplicate directory "/usr/local/include"
ignoring duplicate directory "/Library/Developer/CommandLineTools/usr/bin/../include/c++/v1"
  as it is a non-system directory that duplicates a system directory
ignoring duplicate directory "/usr/local/include"
  as it is a non-system directory that duplicates a system directory
ignoring duplicate directory "/Library/Developer/CommandLineTools/usr/lib/clang/11.0.0/include"
  as it is a non-system directory that duplicates a system directory
ignoring duplicate directory "/Library/Developer/CommandLineTools/usr/include"
  as it is a non-system directory that duplicates a system directory
#include "..." search starts here:
#include <...> search starts here:
 /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include
 /Library/Frameworks/R.framework/Resources/include
 /Library/Frameworks/R.framework/Versions/4.0/Resources/library/Rcpp/include
 /Users/darbyhadley/asf2323
 /Library/Developer/CommandLineTools/usr/bin/../include/c++/v1
 /usr/local/include
 /Library/Developer/CommandLineTools/usr/lib/clang/11.0.0/include
 /Library/Developer/CommandLineTools/usr/include
 /System/Library/Frameworks (framework directory)
 /Library/Frameworks (framework directory)
End of search list.
CLANG INDEXING: /Users/darbyhadley/asf2323/things.cpp
CLANG REMOVE INDEX: /Users/darbyhadley/asf2323/things.cpp
COMPILATION ARGUMENTS:
[
    "-I/Library/Developer/CommandLineTools/usr/lib/clang/11.0.0/include",
    "-I/usr/local/include",
    "-I/Library/Developer/CommandLineTools/usr/bin/../include/c++/v1",
    "-I/Library/Developer/CommandLineTools/usr/lib/clang/11.0.0/include",
    "-I/Library/Developer/CommandLineTools/usr/include",
    "-I/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include",
    "-std=gnu++11",
    "-I/Library/Frameworks/R.framework/Resources/include",
    "-DNDEBUG",
    "-I/Library/Frameworks/R.framework/Versions/4.0/Resources/library/Rcpp/include",
    "-I/Users/darbyhadley/asf2323",
    "-I/usr/local/include",
    "-fPIC",
    "-include-pch",
    "/var/folders/tg/12vm8qdj2l592vg5f9w2ljfh0000gn/T/Rtmp4j56Yp/rstudio/libclang/precompiled/Rcpp/CEDFA90F/1.0.4.6-x86_64-apple-darwin17.0-78648-11.0.0/Rcpp-std=gnu++11.pch",
    "-v"
]
  (Creating new index)
Apple clang version 11.0.0 (clang-1100.0.33.8)
Target: x86_64-apple-darwin19.2.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin
ignoring nonexistent directory "/usr/include/c++/v1"
ignoring nonexistent directory "/usr/include"
ignoring duplicate directory "/Library/Developer/CommandLineTools/usr/lib/clang/11.0.0/include"
ignoring duplicate directory "/usr/local/include"
ignoring duplicate directory "/Library/Developer/CommandLineTools/usr/bin/../include/c++/v1"
  as it is a non-system directory that duplicates a system directory
ignoring duplicate directory "/usr/local/include"
  as it is a non-system directory that duplicates a system directory
ignoring duplicate directory "/Library/Developer/CommandLineTools/usr/lib/clang/11.0.0/include"
  as it is a non-system directory that duplicates a system directory
ignoring duplicate directory "/Library/Developer/CommandLineTools/usr/include"
  as it is a non-system directory that duplicates a system directory
#include "..." search starts here:
#include <...> search starts here:
 /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include
 /Library/Frameworks/R.framework/Resources/include
 /Library/Frameworks/R.framework/Versions/4.0/Resources/library/Rcpp/include
 /Users/darbyhadley/asf2323
 /Library/Developer/CommandLineTools/usr/bin/../include/c++/v1
 /usr/local/include
 /Library/Developer/CommandLineTools/usr/lib/clang/11.0.0/include
 /Library/Developer/CommandLineTools/usr/include
 /System/Library/Frameworks (framework directory)
 /Library/Frameworks (framework directory)
End of search list.
/Library/Developer/CommandLineTools/usr/bin/../include/c++/v1/vector:339:38: error: no type named 'const_pointer' in 'std::__1::allocator_traits<std::__1::allocator<int> >'
/Library/Developer/CommandLineTools/usr/bin/../include/c++/v1/vector:471:15: note: in instantiation of template class 'std::__1::__vector_base<int, std::__1::allocator<int> >' requested here
/Users/darbyhadley/asf2323/things.cpp:4:20: note: in instantiation of template class 'std::__1::vector<int, std::__1::allocator<int> >' requested here
/Library/Developer/CommandLineTools/usr/bin/../include/c++/v1/memory:2220:38: error: no member named 'value' in 'std::__1::is_same<int, std::__1::allocator<int> >'
/Library/Developer/CommandLineTools/usr/bin/../include/c++/v1/vector:345:48: note: in instantiation of template class 'std::__1::__compressed_pair<int, std::__1::allocator<int> >' requested here
/Library/Developer/CommandLineTools/usr/bin/../include/c++/v1/vector:471:15: note: in instantiation of template class 'std::__1::__vector_base<int, std::__1::allocator<int> >' requested here
/Users/darbyhadley/asf2323/things.cpp:4:20: note: in instantiation of template class 'std::__1::vector<int, std::__1::allocator<int> >' requested here
/Library/Developer/CommandLineTools/usr/bin/../include/c++/v1/vector:481:30: error: 'reference' is a protected member of 'std::__1::__vector_base<int, std::__1::allocator<int> >'
/Users/darbyhadley/asf2323/things.cpp:4:20: note: in instantiation of template class 'std::__1::vector<int, std::__1::allocator<int> >' requested here
/Library/Developer/CommandLineTools/usr/bin/../include/c++/v1/vector:335:54: note: declared protected here
/Library/Developer/CommandLineTools/usr/bin/../include/c++/v1/vector:482:30: error: 'const_reference' is a protected member of 'std::__1::__vector_base<int, std::__1::allocator<int> >'
/Library/Developer/CommandLineTools/usr/bin/../include/c++/v1/vector:336:54: note: declared protected here
/Library/Developer/CommandLineTools/usr/bin/../include/c++/v1/vector:484:30: error: 'difference_type' is a protected member of 'std::__1::__vector_base<int, std::__1::allocator<int> >'
/Library/Developer/CommandLineTools/usr/bin/../include/c++/v1/vector:337:54: note: declared protected here
/Library/Developer/CommandLineTools/usr/bin/../include/c++/v1/vector:485:30: error: 'pointer' is a protected member of 'std::__1::__vector_base<int, std::__1::allocator<int> >'
/Library/Developer/CommandLineTools/usr/bin/../include/c++/v1/vector:338:54: note: declared protected here
/Library/Developer/CommandLineTools/usr/bin/../include/c++/v1/vector:486:30: error: 'const_pointer' is a protected member of 'std::__1::__vector_base<int, std::__1::allocator<int> >'
/Library/Developer/CommandLineTools/usr/bin/../include/c++/v1/vector:339:54: note: declared protected here
/Library/Developer/CommandLineTools/usr/bin/../include/c++/v1/vector:492:78: error: no member named 'value' in 'std::__1::is_same<int, int>'
/Users/darbyhadley/asf2323/things.cpp:6:1: error: expected unqualified-id
TOTAL MEMORY: 27 mb (things.cpp)
PERFORMANCE 25 ms (things.cpp)
```

**Comment by kevinushey** [comment]
Thanks! I'm now able to reproduce.

@dfalty: can you try the following, to see if it alleviates the issue?

```
cat("SDKROOT = /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk", file = "~/.Renviron", append = TRUE)
```

After running that code, try restarting the R session and re-requesting completions.

**Comment by dfalty** [comment]
@kevinushey that did the trick! Tried this on 1.3.1045.

**Comment by dfalty** [comment]
Removed the line from ~/.Renviron and verified the fix in 1.3.1054.
