### ISSUE TITLE
RStudio Viewer doesn't accept ES6

### ISSUE THREAD

**Issue by trafficonese** [rstudio/rstudio#11900]
### System details

    RStudio Edition : Desktop 
    RStudio Version : 2022.07.1 Build 554
    RStudio 2022.07.1+554 "Spotted Wakerobin" Release (7872775ebddc40635780ca1ed238934c3345c5de, 2022-07-22) for Windows
    Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) QtWebEngine/5.12.8 Chrome/69.0.3497.128 
    Safari/537.36
    OS Version      :  "Windows 10 x64 (build 22000)"
    R Version       :  R version 4.2.0

### Steps to reproduce the problem

Using a JavaScript library that is written in ES6 won't work in the Viewer, but works in a Shiny environment.

RStudio viewer version:
```
library(leaflet)
library(leaflet.extras2)
leaflet() %>% addTiles() %>% 
    addArrowhead(data = atlStorms2005)
```

Shiny version:
```
library(shiny)  
library(leaflet)
library(leaflet.extras2)

ui <- fluidPage(leafletOutput("map"))

server <- function(input, output, session) {
  output$map <- renderLeaflet({
    leaflet() %>% addTiles() %>% 
      addArrowhead(data = atlStorms2005)
  })
}
shinyApp(ui, server)
```

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [ ] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by jmcphers** [comment]
> won't work in the Viewer

Could you be more specific? Are there any errors? What do you see in the Viewer when it isn't working?

It could be a problem with RStudio's older Web rendering engine. If you're willing to try it, we have a build with a new rendering engine here: 

https://dailies.rstudio.com/rstudio/elsbeth-geranium/electron/windows/

**Comment by kevinushey** [comment]
For reference, this does indeed work in the latest daily builds of RStudio.

**Comment by trafficonese** [comment]
@jmcphers Yes there are errors in the console and only the background Tiles appear in the Viewer but no polylines with arrowheads.
```
Uncaught SyntaxError: Unexpected token .                                                    leaflet-arrowheads.js:134
Uncaught TypeError: L.polyline(...).arrowheads is not a function                    leaflet-arrowheads-bindings.js:22
```

This is line 134 of `leaflet-arrowheads.js`
```
if (offsets?.start || offsets?.end) {
```

I can confirm, that it works correctly with Rstudio 2022.11.0 Build 166
