### ISSUE TITLE
Error rendering Quarto document with 'highlight-style: haddock' 

### ISSUE THREAD

**Issue by brainfood** [rstudio/rstudio#13075]
Starting with version v2022.12.0+353 of Rstudio, when I attempt to render a quarto document with the haddock highlight style, I get the following error:

```
ERROR: Theme file compilation failed:

Error: $color: undefined is not a color.
    ╷
449 │   @return "rgb(" + red($color) + ", " + green($color) + ", " + blue($color) +
    │                    ^^^^^^^^^^^
    ╵
  C:\Users\Username\AppData\Local\Temp\quarto-session610b33a0\ef702a45\000a83d1.scss 449:20    colorToRGB()
```

This error appears in the 'Background Jobs' tab and the document fails to render. I've encountered this across multiple computers running Windows 10, running multiple versions of R, and with Rstudio versions v2022.12.0+353 and v2023.03.0+386. Rstudio version v2022.07.2+576 is the last one I could use without generating this error.

Here's code for a minimal Quarto doc that causes the error for me:

```
---
title: "Render fails with highlight-style: haddock"
format:
    html:
        highlight-style: haddock
---

This quarto doc fails when I try to render it in Rstudio
```

The issue arises from the header at the top of the quarto doc. The document renders without error if I remove the highlight-style line from the header, or if I set it to something else like 'github' or 'tango'. I haven't exhaustively checked to see if this is just an issue with the haddock style. 

Here's the R session info from my latest attempt to render this doc:

```
R version 4.2.2 (2022-10-31 ucrt)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 19044)

Matrix products: default

locale:
[1] LC_COLLATE=English_United States.utf8 
[2] LC_CTYPE=English_United States.utf8   
[3] LC_MONETARY=English_United States.utf8
[4] LC_NUMERIC=C                          
[5] LC_TIME=English_United States.utf8    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
 [1] digest_0.6.31     lifecycle_1.0.3   jsonlite_1.8.4    magrittr_2.0.3   
 [5] evaluate_0.19     rlang_1.0.6       stringi_1.7.12    cli_3.6.0        
 [9] rstudioapi_0.14   vctrs_0.5.1       rmarkdown_2.19    tools_4.2.2      
[13] stringr_1.5.0     glue_1.6.2        htmlwidgets_1.6.1 xfun_0.39        
[17] yaml_2.3.6        fastmap_1.1.0     compiler_4.2.2    htmltools_0.5.4  
[21] knitr_1.41
```

I recognize this could be a Quarto issue, but figured I'd start here. I appreciate any help you can offer.

**Comment by ronblum** [comment]
@brainfood Thank you for raising this! I can reproduce the problem. Your suggestion that this is an issue with Quarto, not RStudio, is correct: Rendering fails using the Quarto command line interfact, e.g. 
```
ronblum@Rons-Busy-Bee ~ % quarto --version
1.2.475
ronblum@Rons-Busy-Bee ~ % quarto render haddock.qmd
ERROR: Theme file compilation failed:

Error: $color: undefined is not a color.
    ╷
449 │   @return "rgb(" + red($color) + ", " + green($color) + ", " + blue($color) +
    │                    ^^^^^^^^^^^
    ╵
  /var/folders/v6/fy__w63j2b3fm1h6vfs6nqg80000gn/T/quarto-session3d1105b9/a5a72bba/b9c20a93.scss 449:20    colorToRGB()
```

This worked in version 1.1.189 of Quarto (bundled with RStudio 2022.07.2+576), fails in Quarto 1.2.475 (bundled with RStudio 2023.03.1+434), and works again with Quarto 1.3.340.

There are two ways to get it:
1) Download the current version of the Quarto CLI at https://quarto.org/docs/get-started/
2) Try [a daily build for the RStudio release](https://dailies.rstudio.com/) currently in progress, Mountain Hydrangea 2023.05, which bundles Quarto 1.3.340. Please note that these are for testing purposes only and should not be used for production work.
