### ISSUE TITLE
Fails to build with Boost 1.70.0

### ISSUE THREAD

**Issue by jbeich** [rstudio/rstudio#4467]
Regressed by boostorg/asio@a72fbb0b867f. Also affected by zaphoyd/websocketpp#794.
```c++
In file included from src/cpp/session/postback/PostbackMain.cpp:36:
In file included from src/cpp/session/include/session/http/SessionRequest.hpp:24:
In file included from src/cpp/core/include/core/http/TcpIpBlockingClient.hpp:22:
In file included from src/cpp/core/include/core/http/TcpIpAsyncClient.hpp:28:
src/cpp/core/include/core/http/TcpIpAsyncConnector.hpp:80:76: error: no member named 'get_io_service' in
      'boost::asio::ip::basic_resolver<boost::asio::ip::tcp, boost::asio::executor>'
         pConnectionTimer_.reset(new boost::asio::deadline_timer(resolver_.get_io_service(), timeout));
                                                                 ~~~~~~~~~ ^
1 error generated.
```

**Comment by ivr588** [comment]
Does https://github.com/Icinga/icinga2/issues/7041 suggest the problem might be fixed?

**Comment by jbeich** [comment]
Fixed by #5353.

**Comment by Flamefire** [comment]
This is still an issue in 1.2.5033: https://github.com/rstudio/rstudio/blob/v1.2.5033/src/cpp/core/include/core/http/TcpIpAsyncConnector.hpp#L80

**Comment by gtritchie** [comment]
This change will not be backported to 1.2, that version only receives critical fixes. It is part of under-development 1.3 release, currently on master.

These builds are shown at https://dailies.rstudio.com/

**Comment by Flamefire** [comment]
Any reason why not? 1.3 is not released, so having a simple fix for a build failure in the old release branch would be great. A cherry-pick works w/o issues, so effort is low.

I'd understand the " only  critical fixes" policy if there was an active other release, but there isn't.

**Comment by gtritchie** [comment]
It’s a slippery slope. There are many simple fixes that someone would like backported (including me) and there is a non-trivial cost of building and releasing a new supported version. There are downstream products of RStudio which also have to be rebuilt, retested, and so forth to do a new release. 1.3 is nearing end of development and will enter preview stage soon.
