### ISSUE TITLE
Building Arch Linux RStudio Server package breaks at commit `c864a187` (Fri Jul 10, 10:02:01 2020 -0500)

### ISSUE THREAD

**Issue by mark-andrews** [rstudio/rstudio#7333]
### System details

    RStudio Edition : Server
    RStudio Version : v1.3.959-3559-g6a2e1ebf0a (from `git describe --tags`)
    OS Version      : Linux (Arch)
    R Version       : 4.0.2

### Steps to reproduce the problem

A Dockerfile that reproduces the problem is available [here](https://gist.github.com/mark-andrews/56812ff397178698574459acd8233388#file-dockerfile). Specifically, the error occurs at the end of the build that is done with the `makepkg` command on [this line](https://gist.github.com/mark-andrews/56812ff397178698574459acd8233388#file-dockerfile-L28)

### Describe the problem in detail

Building a Arch Linux package for RStudio Server that is based on the latest commit to this repository breaks with the following error message:
```
[ 98%] Building CXX object src/cpp/server/CMakeFiles/rserver.dir/auth/ServerAuthHandler.cpp.o
/home/builder/rstudio-server-git/src/rstudio/src/cpp/server/auth/ServerAuthHandler.cpp:338:16: error: ‘rstudio::core::Error rstudio::server::auth::handler::overlay::setAdmin’ redeclared as different kind of entity
  338 | Error setAdmin(rstudio_boost::asio::io_service& ioService,
      |                ^~~~~~~~~~~~~
In file included from /home/builder/rstudio-server-git/src/rstudio/src/cpp/server/auth/ServerAuthHandler.cpp:19:
/home/builder/rstudio-server-git/src/rstudio/src/cpp/server/include/server/auth/ServerAuthHandler.hpp:146:13: note: previous declaration ‘rstudio::core::Error rstudio::server::auth::handler::overlay::setAdmin(boost::asio::io_service&, const string&, bool)’
  146 | core::Error setAdmin(boost::asio::io_service& ioService, const std::string& username, bool isAdmin);
      |             ^~~~~~~~
/home/builder/rstudio-server-git/src/rstudio/src/cpp/server/auth/ServerAuthHandler.cpp:338:16: error: ‘rstudio_boost’ has not been declared
  338 | Error setAdmin(rstudio_boost::asio::io_service& ioService,
      |                ^~~~~~~~~~~~~
/home/builder/rstudio-server-git/src/rstudio/src/cpp/server/auth/ServerAuthHandler.cpp:338:49: error: ‘ioService’ was not declared in this scope
  338 | Error setAdmin(rstudio_boost::asio::io_service& ioService,
      |                                                 ^~~~~~~~~
/home/builder/rstudio-server-git/src/rstudio/src/cpp/server/auth/ServerAuthHandler.cpp:339:16: error: expected primary-expression before ‘const’
  339 |                const std::string& username,
      |                ^~~~~
/home/builder/rstudio-server-git/src/rstudio/src/cpp/server/auth/ServerAuthHandler.cpp:340:16: error: expected primary-expression before ‘bool’
  340 |                bool isAdmin)
      |                ^~~~
/home/builder/rstudio-server-git/src/rstudio/src/cpp/server/auth/ServerAuthHandler.cpp:345:15: error: ‘rstudio::core::Error rstudio::server::auth::handler::overlay::addUser’ redeclared as different kind of entity
  345 | Error addUser(rstudio_boost::asio::io_service& ioService,
      |               ^~~~~~~~~~~~~
In file included from /home/builder/rstudio-server-git/src/rstudio/src/cpp/server/auth/ServerAuthHandler.cpp:19:
/home/builder/rstudio-server-git/src/rstudio/src/cpp/server/include/server/auth/ServerAuthHandler.hpp:147:13: note: previous declaration ‘rstudio::core::Error rstudio::server::auth::handler::overlay::addUser(boost::asio::io_service&, const string&, bool)’
  147 | core::Error addUser(boost::asio::io_service& ioService, const std::string& username, bool isAdmin);
      |             ^~~~~~~
/home/builder/rstudio-server-git/src/rstudio/src/cpp/server/auth/ServerAuthHandler.cpp:345:15: error: ‘rstudio_boost’ has not been declared
  345 | Error addUser(rstudio_boost::asio::io_service& ioService,
      |               ^~~~~~~~~~~~~
/home/builder/rstudio-server-git/src/rstudio/src/cpp/server/auth/ServerAuthHandler.cpp:345:48: error: ‘ioService’ was not declared in this scope
  345 | Error addUser(rstudio_boost::asio::io_service& ioService,
      |                                                ^~~~~~~~~
/home/builder/rstudio-server-git/src/rstudio/src/cpp/server/auth/ServerAuthHandler.cpp:346:15: error: expected primary-expression before ‘const’
  346 |               const std::string& username,
      |               ^~~~~
/home/builder/rstudio-server-git/src/rstudio/src/cpp/server/auth/ServerAuthHandler.cpp:347:15: error: expected primary-expression before ‘bool’
  347 |               bool isAdmin)
      |               ^~~~
make[2]: *** [src/cpp/server/CMakeFiles/rserver.dir/build.make:317: src/cpp/server/CMakeFiles/rserver.dir/auth/ServerAuthHandler.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:893: src/cpp/server/CMakeFiles/rserver.dir/all] Error 2
make: *** [Makefile:172: all] Error 2
==> ERROR: A failure occurred in package().
    Aborting...

```

A `git bisect` between the most recent commit and the last known commit where the build was successful shows that the problem occurs at commit `c864a187`:

```
c864a1871dc7746c1383c2a8dfbeb670ee4b643f is the first bad commit
commit c864a1871dc7746c1383c2a8dfbeb670ee4b643f
Author: karl@rstudio.com <karl@rstudio.com>
Date:   Fri Jul 10 10:02:01 2020 -0500

    Open source companion commit for https://github.com/rstudio/rstudio-pro/pull/1763

 src/cpp/server/auth/ServerAuthHandler.cpp          | 24 ++++++++++++++++++++++
 .../include/server/auth/ServerAuthHandler.hpp      |  4 ++++
 2 files changed, 28 insertions(+)
```

### Describe the behavior you expected

Expected behaviour is an Arch Linux package installer. The most recent commit which leads to a successful build is `df9e6d3` which is just prior to `c864a18`.

- [x] I have read the guide to submitting good bug reports at https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports . 
- [x] I have installed the latest version of RStudio and confirmed that the issue still persists.
- [ ] If I am reporting a RStudio crash, I have included a diagnostics report. https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by kevinushey** [comment]
Thanks for the bug report -- I believe we should be using the `boost` namespace here rather than `rstudio_boost`.

**Comment by kfeinauer** [comment]
I'll fix this - unfortunately my IDE autocompletes the `rstudio_boost` namespace, and I didn't catch it.

**Comment by kfeinauer** [comment]
Also, this only exists in master (1.4).

**Comment by kfeinauer** [comment]
Fixed in ce0c001

**Comment by R-Hannibal** [comment]
@mark-andrews, thanks again for finding and reporting this issue. 

We have a fix in place in our latest Daily build of the upcoming 1.4 release of RStudio (available [HERE](https://dailies.rstudio.com/)). If you get the chance will you let us know if the issue is resolved for you in that build?

**Comment by stephensrmmartin** [comment]
Just FYI, this is also fixed.

**Comment by stephensrmmartin** [comment]
@R-Hannibal Just FYI, this is also fixed.

**Comment by R-Hannibal** [comment]
@stephensrmmartin - you're awesome, thanks so much again for the assist. I cannot overstate how much we appreciate and value the amazing RStudio community, and in particular users like yourself that actively help us to improve the RStudio experience for everyone.

Marking this issue as verified.

**Comment by stephensrmmartin** [comment]
Thanks; you may also want to know about a fellow maintainer's rstudio project repo: https://gitlab.com/aur1/rstudio/-/tree/master
The pkgs are all on AUR, but they made a binary repo for them with continuous integration. Arch linux users are basically your beta-testers, since a number of use the git master 'releases' with system libs.
