### PR TITLE
Inspection of incorrect localization

### PR DESCRIPTION
**Pull request by rohank07**
### Intent

> Describe briefly what problem this pull request resolves, or what new feature it introduces. Include screenshots of any new or altered UI. Link to any Github issues that are related. 

https://github.com/StatCan/daaas/issues/816
Did more cleaning up of unused literals. Regarding the over-localization of strings that are actually not user-facing (e.g. string-value enums); I found a few more examples but wanted to verify with you first. These exist in:
- NewPackagePage.java (95)
- NewQuartoProjectPage.java (87, 110)
- ConsolePreferencesPane.java (48)
- RMarkdownPreferencesPane.java (85, 102, 127, 146)
- TerminalPerferencesPane.java (79, 201)
- EditingPreferencesPane.java 
- GeneralPrefernencesPane.java (159,218,240)

### Approach

> Describe the approach taken and the tradeoffs involved if non-obvious; add an overview of the solution if it's complicated.

### Automated Tests

> Indicate whether this change includes unit tests or integration tests, or link a work item or pull request to add those tests to another repo. If the change cannot or will not be covered by a test, indicate why.

### QA Notes

> Add additional information for QA on how to validate the change, paying special attention to the level of risk, adjacent areas that could be affected by the change, and any important contextual information not present in the linked issues. 

### Checklist

- [ ] If this PR adds a new feature, or fixes a bug in a previously released version, it includes an entry in `NEWS.md` 
- [X] If this PR adds or changes UI, the updated UI meets [accessibility standards](https://github.com/rstudio/rstudio/wiki/Accessibility)
- [ ] A reviewer is assigned to this PR (if unsure who to assign, check Area Owners list)
- [ ] This PR passes all local unit tests

cc @gtritchie

### CODE REVIEW

**Review by gtritchie — CHANGES_REQUESTED** [review]
I tried building this branch, after merging in all the latest changes from upstream main, and get numerous errors:

```
javac:
    [javac] Compiling 887 source files to /Users/gary/alt/loc/rstudio/src/gwt/bin
    [javac] /Users/gary/alt/loc/rstudio/src/gwt/src/org/rstudio/studio/client/workbench/prefs/views/EditingPreferencesPane.java:98: error: cannot find symbol
    [javac]       SmallButton editShortcuts = new SmallButton(constants_.editingEditShortcuts());
    [javac]                                                             ^
    [javac]   symbol:   method editingEditShortcuts()
    [javac]   location: variable constants_ of type PrefsConstants
    [javac] /Users/gary/alt/loc/rstudio/src/gwt/src/org/rstudio/studio/client/workbench/prefs/views/EditingPreferencesPane.java:113: error: cannot find symbol
    [javac]       Label executionLabel = headerLabel(constants_.editingExecutionLabel());
    [javac]                                                    ^
    [javac]   symbol:   method editingExecutionLabel()
    [javac]   location: variable constants_ of type PrefsConstants
    [javac] /Users/gary/alt/loc/rstudio/src/gwt/src/org/rstudio/studio/client/workbench/prefs/views/EditingPreferencesPane.java:129: error: cannot find symbol
    [javac]       Label snippetsLabel = headerLabel(constants_.editingSnippetsLabel());
    [javac]                                                   ^
    [javac]   symbol:   method editingSnippetsLabel()
    [javac]   location: variable constants_ of type PrefsConstants
    [javac] /Users/gary/alt/loc/rstudio/src/gwt/src/org/rstudio/studio/client/workbench/prefs/views/EditingPreferencesPane.java:149: error: cannot find symbol
    [javac]       HelpButton snippetHelp = new HelpButton("code_snippets", constants_.editingSnippetHelpTitle());
    [javac]                                                                          ^
    [javac]   symbol:   method editingSnippetHelpTitle()
    [javac]   location: variable constants_ of type PrefsConstants
    [javac] /Users/gary/alt/loc/rstudio/src/gwt/src/org/rstudio/studio/client/workbench/prefs/views/EditingPreferencesPane.java:186: error: cannot find symbol
    [javac]       Label serializationLabel = headerLabel(constants_.editingSerializationLabel());
    [javac]                                                        ^
    [javac]   symbol:   method editingSerializationLabel()
    [javac]   location: variable constants_ of type PrefsConstants
    [javac] /Users/gary/alt/loc/rstudio/src/gwt/src/org/rstudio/studio/client/workbench/prefs/views/EditingPreferencesPane.java:199: error: cannot find symbol
    [javac]             constants_.editingSavePanelAction(),
    [javac]                       ^
    [javac]   symbol:   method editingSavePanelAction()
    [javac]   location: variable constants_ of type PrefsConstants
    [javac] /Users/gary/alt/loc/rstudio/src/gwt/src/org/rstudio/studio/client/workbench/prefs/views/EditingPreferencesPane.java:238: error: cannot find symbol
    [javac]       savePanel.add(spacedBefore(headerLabel(constants_.editingSavePanelAutosave())));
    [javac]                                                        ^
    [javac]   symbol:   method editingSavePanelAutosave()
    [javac]   location: variable constants_ of type PrefsConstants
    [javac] /Users/gary/alt/loc/rstudio/src/gwt/src/org/rstudio/studio/client/workbench/prefs/views/EditingPreferencesPane.java:275: error: cannot find symbol
    [javac]       completionPanel.add(headerLabel(constants_.editingCompletionPanel()));
    [javac]                                                 ^
    [javac]   symbol:   method editingCompletionPanel()
    [javac]   location: variable constants_ of type PrefsConstants
    [javac] /Users/gary/alt/loc/rstudio/src/gwt/src/org/rstudio/studio/client/workbench/prefs/views/EditingPreferencesPane.java:318: error: cannot find symbol
    [javac]       Label otherLabel = headerLabel(constants_.editingDiagOtherLabel());
    [javac]                                                ^
    [javac]   symbol:   method editingDiagOtherLabel()
    [javac]   location: variable constants_ of type PrefsConstants
    [javac] /Users/gary/alt/loc/rstudio/src/gwt/src/org/rstudio/studio/client/workbench/prefs/views/EditingPreferencesPane.java:328: error: cannot find symbol
    [javac]       Label otherTip = new Label(constants_.editingOtherTip());
    [javac]                                            ^
    [javac]   symbol:   method editingOtherTip()
    [javac]   location: variable constants_ of type PrefsConstants
    [javac] /Users/gary/alt/loc/rstudio/src/gwt/src/org/rstudio/studio/client/workbench/prefs/views/EditingPreferencesPane.java:333: error: cannot find symbol
    [javac]       Label delayLabel = headerLabel(constants_.editingHeaderLabel());
    [javac]                                                ^
    [javac]   symbol:   method editingHeaderLabel()
    [javac]   location: variable constants_ of type PrefsConstants
    [javac] /Users/gary/alt/loc/rstudio/src/gwt/src/org/rstudio/studio/client/workbench/prefs/views/EditingPreferencesPane.java:344: error: cannot find symbol
    [javac]       diagnosticsPanel.add(headerLabel(constants_.editingDiagnosticsPanel()));
    [javac]                                                  ^
    [javac]   symbol:   method editingDiagnosticsPanel()
    [javac]   location: variable constants_ of type PrefsConstants
    [javac] /Users/gary/alt/loc/rstudio/src/gwt/src/org/rstudio/studio/client/workbench/prefs/views/EditingPreferencesPane.java:367: error: cannot find symbol
    [javac]       Label diagOtherLabel = headerLabel(constants_.editingOtherLabel());
    [javac]                                                    ^
    [javac]   symbol:   method editingOtherLabel()
    [javac]   location: variable constants_ of type PrefsConstants
    [javac] /Users/gary/alt/loc/rstudio/src/gwt/src/org/rstudio/studio/client/workbench/prefs/views/EditingPreferencesPane.java:372: error: cannot find symbol
    [javac]       Label diagShowLabel = headerLabel(constants_.editingDiagShowLabel());
    [javac]                                                   ^
    [javac]   symbol:   method editingDiagShowLabel()
    [javac]   location: variable constants_ of type PrefsConstants
    [javac] /Users/gary/alt/loc/rstudio/src/gwt/src/org/rstudio/studio/client/workbench/prefs/views/EditingPreferencesPane.java:385: error: cannot find symbol
    [javac]       DialogTabLayoutPanel tabPanel = new DialogTabLayoutPanel(constants_.editingTabPanel());
    [javac]                                                                          ^
    [javac]   symbol:   method editingTabPanel()
    [javac]   location: variable constants_ of type PrefsConstants
    [javac] /Users/gary/alt/loc/rstudio/src/gwt/src/org/rstudio/studio/client/workbench/prefs/views/EditingPreferencesPane.java:387: error: cannot find symbol
    [javac]       tabPanel.add(editingPanel, constants_.editingTabPanel(), editingPanel.getBasePanelId());
    [javac]                                            ^
    [javac]   symbol:   method editingTabPanel()
    [javac]   location: variable constants_ of type PrefsConstants
    [javac] /Users/gary/alt/loc/rstudio/src/gwt/src/org/rstudio/studio/client/workbench/prefs/views/EditingPreferencesPane.java:388: error: cannot find symbol
    [javac]       tabPanel.add(displayPanel, constants_.editingTabPanelDisplayPanel(), displayPanel.getBasePanelId());
    [javac]                                            ^
    [javac]   symbol:   method editingTabPanelDisplayPanel()
    [javac]   location: variable constants_ of type PrefsConstants
    [javac] /Users/gary/alt/loc/rstudio/src/gwt/src/org/rstudio/studio/client/workbench/prefs/views/EditingPreferencesPane.java:389: error: cannot find symbol
    [javac]       tabPanel.add(savePanel, constants_.editingTabPanelSavePanel(), savePanel.getBasePanelId());
    [javac]                                         ^
    [javac]   symbol:   method editingTabPanelSavePanel()
    [javac]   location: variable constants_ of type PrefsConstants
    [javac] /Users/gary/alt/loc/rstudio/src/gwt/src/org/rstudio/studio/client/workbench/prefs/views/EditingPreferencesPane.java:390: error: cannot find symbol
    [javac]       tabPanel.add(completionPanel, constants_.editingTabPanelCompletionPanel(), completionPanel.getBasePanelId());
    [javac]                                               ^
    [javac]   symbol:   method editingTabPanelCompletionPanel()
    [javac]   location: variable constants_ of type PrefsConstants
    [javac] /Users/gary/alt/loc/rstudio/src/gwt/src/org/rstudio/studio/client/workbench/prefs/views/EditingPreferencesPane.java:391: error: cannot find symbol
    [javac]       tabPanel.add(diagnosticsPanel, constants_.editingTabPanelDiagnosticsPanel(), diagnosticsPanel.getBasePanelId());
    [javac]                                                ^
    [javac]   symbol:   method editingTabPanelDiagnosticsPanel()
    [javac]   location: variable constants_ of type PrefsConstants
    [javac] 20 errors
```

**Comment by rohank07** [comment]
Sorry about that. Should be good now!

**Review by gtritchie — CHANGES_REQUESTED** [review]
Cleanup looks good.

For the over-localization questions:

- NewPackagePage.java (95)
    - The "value" should not be localized and should be reverted to:
```
      String[] values = {"package"};
```
- GeneralPrefernencesPane.java (159,218,240)
    - 159 and 218 look ok to me
    - 240, that should have the second array ("values") switched back to:
 ```
            new String[] {
                 "sessions",
                 "always",
                 "never"
            },
```
- NewQuartoProjectPage.java (87, 110)
- ConsolePreferencesPane.java (48)
- RMarkdownPreferencesPane.java (85, 102, 127, 146)
- TerminalPerferencesPane.java (79, 201)
- EditingPreferencesPane.java
    - These all look OK to me, the "values" are already non-localized constants, and the "options" which are shown in the UI are localizable

**Review by gtritchie — APPROVED** [review]
