### ISSUE TITLE
R Studio 1.456 won't compile with Boost 1.68.0 on openSUSE

### ISSUE THREAD

**Issue by Mailaender** [rstudio/rstudio#3770]
```
[  130s] /home/abuild/rpmbuild/BUILD/rstudio-1.1.456/src/cpp/core/DateTime.cpp: In function 'boost::posix_time::ptime rstudio::core::date_time::timeFromSecondsSinceEpoch(double)':
[  130s] /home/abuild/rpmbuild/BUILD/rstudio-1.1.456/src/cpp/core/DateTime.cpp:68:37: error: no matching function for call to 'boost::posix_time::seconds::seconds(double&)'
[  130s]     return time_t_epoch + seconds(sec);
[  130s]                                      ^
[  130s] In file included from /usr/include/boost/date_time/posix_time/posix_time_types.hpp:16,
[  130s]                  from /usr/include/boost/date_time/posix_time/time_formatters.hpp:16,
[  130s]                  from /usr/include/boost/date_time/posix_time/posix_time.hpp:24,
[  130s]                  from /home/abuild/rpmbuild/BUILD/rstudio-1.1.456/src/cpp/core/include/core/DateTime.hpp:21,
[  130s]                  from /home/abuild/rpmbuild/BUILD/rstudio-1.1.456/src/cpp/core/DateTime.cpp:16:
[  130s] /usr/include/boost/date_time/posix_time/posix_time_duration.hpp:57:16: note: candidate: 'template<class T> boost::posix_time::seconds::seconds(const T&, typename boost::enable_if<boost::is_integral<T> >::type*)'
[  130s]        explicit seconds(T const& s,
[  130s]                 ^~~~~~~
[  130s] /usr/include/boost/date_time/posix_time/posix_time_duration.hpp:57:16: note:   template argument deduction/substitution failed:
[  130s] /usr/include/boost/date_time/posix_time/posix_time_duration.hpp: In substitution of 'template<class T> boost::posix_time::seconds::seconds(const T&, typename boost::enable_if<boost::is_integral<T> >::type*) [with T = double]':
[  130s] /home/abuild/rpmbuild/BUILD/rstudio-1.1.456/src/cpp/core/DateTime.cpp:68:37:   required from here
[  130s] /usr/include/boost/date_time/posix_time/posix_time_duration.hpp:57:16: error: no type named 'type' in 'struct boost::enable_if<boost::is_integral<double>, void>'
```

**Comment by ronblum** [comment]
@Mailaender Thanks for raising the issue. Are you able to compile the latest 1.2 dailies?

**Comment by Mailaender** [comment]
Yes, v1.2.679 builds fine https://build.opensuse.org/request/show/661353 and is currently on it's way to be included with @openSUSE Tumbleweed.

**Comment by kevinushey** [comment]
@Mailaender we would recommend using the latest preview release of RStudio (the current release is available at https://www.rstudio.com/products/rstudio/download/preview/).

v1.2.679 is rather old at this point and so you may be subjecting users to transient bugs which may have since been fixed in the latest preview release.
