### ISSUE TITLE
R < 4.0 interactive sessions: PCRE UTF error after GlobalCallingHandlers.R sourced unconditionally in RInit.cpp

### ISSUE THREAD

**Issue by astayleraz** [rstudio/rstudio#17840]
### System details

    RStudio Edition : Workbench (Server Pro)
    RStudio Version : 2025.05.0 through 2026.04.0+ (all versions since GlobalCallingHandlers.R was added)
    OS Version      : RHEL 8 / RHEL 9 / Rocky 9 (any system where R 3.x links PCRE1)
    R Version       : Any R < 4.0.0 compiled against PCRE1 (-lpcre in Makeconf)

### Steps to reproduce the problem

In an interactive Workbench session with R 3.6.x as the session R:

1. Start a new interactive session
2. At the first console prompt, run:

```r
strsplit("ax", "(?=\\S)", perl=TRUE)
```

Expected: `list(c("a", "x"))`  
Actual: PCRE pattern compilation error (see below)

Alternatively, in bare R 3.6.x with the Workbench R files present:

```r
source("/usr/lib/rstudio-server/R/GlobalCallingHandlers.R", encoding="UTF-8")
strsplit("ax", "(?=\\S)", perl=TRUE)
```

### Describe the problem in detail

`RInit.cpp:252-255` unconditionally sources `GlobalCallingHandlers.R` for all R versions:

```cpp
FilePath globalCallingHandlersFilePath = utils::rSourcePath().completePath("GlobalCallingHandlers.R");
error = r::sourceManager().sourceTools(globalCallingHandlersFilePath);
```

However, `SessionInit.cpp:43` correctly gates handler **activation** with `isR4()`. The asymmetry — sourcing ungated, activation gated — means R < 4.0 sessions source a file that serves no purpose for them.

`GlobalCallingHandlers.R` was introduced in commit `ea9a15dba5` (2025-03-31), making v2025.05.0 the first affected release. The file is absent from v2024.12.1 and earlier (confirmed via `git ls-tree`).

On R 3.6.x (which links PCRE1 via `-lpcre`), sourcing this file via `source(..., encoding="UTF-8")` causes a parse-flag leak that corrupts R's global PCRE UTF flag for the session lifetime. Any subsequent `perl=TRUE` PCRE call then fails with:

```
Error in strsplit("ax", "(?=\\S)", perl = TRUE) :
  invalid split pattern '(?=\S)'
Warning message:
PCRE pattern compilation error
    'this version of PCRE is compiled without UTF support'
    at '(?=\S)'
```

The system PCRE1 library itself has full UTF support (`PCRE_CONFIG_UTF8=1`) — the error message is misleading. The bug is entirely in session init.

**Scope:**
- Affected: all interactive Workbench sessions on R 3.5.x and R 3.6.x
- Unaffected: R 4.x (uses PCRE2, not PCRE1; calling handlers work correctly)
- Unaffected: non-interactive Rscript / Workbench Jobs / Connect (no session init path)
- Reproduced independently on Rocky 9.7 with stock Workbench and empty rsession-profile

A secondary version gate in `SessionCodeTools.R:2475` (`if (getRversion() < "3.5.2") Sys.setlocale()`) was added for a 2018 issue but is too narrow — it excludes R 3.6.x from the recovery path.

### Describe the behavior you expected

`perl=TRUE` patterns should work correctly in R 3.6.x interactive sessions. R 3.6.x on the same host works correctly when run outside of a Workbench session.

### Fix

**Primary (preferred):** Gate sourcing with `isR4()` in `RInit.cpp` around line 252 — consistent with how activation is already gated in `SessionInit.cpp:43`:

```cpp
if (r::session::utils::isR4())
{
   FilePath globalCallingHandlersFilePath = utils::rSourcePath().completePath("GlobalCallingHandlers.R");
   error = r::sourceManager().sourceTools(globalCallingHandlersFilePath);
   if (error)
      return error;
}
```

**Secondary (belt-and-suspenders):** In `SessionCodeTools.R:2475`, extend the version gate from `< "3.5.2"` to `< "4.0.0"`.

**Backport needed:** All releases from 2025.05.0 through current are affected.

Internal ref: IDEESC-731

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [ ] If I am reporting an RStudio crash, I have included a diagnostics report.
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by astayleraz** [comment]
**Dev renv workaround tested — not viable**

After filing this issue, we tested whether installing the development version of renv would serve as a workaround while the Workbench-level fix is developed.

**What we tried:**

In a fresh R 3.6.3 interactive Workbench session (PCRE flag already corrupted by session init):

```r
Sys.setlocale("LC_ALL", "C")
install.packages("remotes")
remotes::install_github("rstudio/renv")
```

Then started a new R 3.6.3 session (no locale workaround applied) and ran:

```r
library(renv)
```

**Result:**

```
Attaching package: 'renv'

Error in strsplit(x, "\n[ \t\n]*\n", perl = TRUE) :
  invalid split pattern '
[     
]*
'
Warning message:
In strsplit(x, "\n[ \t\n]*\n", perl = TRUE) :
  PCRE pattern compilation error
    'this version of PCRE is compiled without UTF support'
    at '
[     
]*
'
```

The original error (`strsplit(contents, "\\r?\\n(?=\\S)", perl=TRUE)`) no longer appears, so the dev renv fix addressed that specific call. However, at least one more `perl=TRUE` call in renv's `.onLoad` path (`strsplit(x, "\n[ \t\n]*\n", perl=TRUE)`) also fails.

**Conclusion:** This is expected given the root cause — the PCRE UTF flag is globally corrupted for the session lifetime, so every `perl=TRUE` call fails regardless of the specific pattern. Patching individual patterns in renv is whack-a-mole. The only reliable fix is the Workbench-level change described in the issue: gate `GlobalCallingHandlers.R` sourcing with `isR4()` in `RInit.cpp`.

**Comment by kevinushey** [comment]
Diagnosis in https://github.com/rstudio/rstudio/issues/17841.

**Comment by astayleraz** [comment]
I verified I was able to run `strsplit("ax", "(?=\\S)", perl=TRUE)` in rhel9 now with `2026.06.0 Build 143`

<img width="1134" height="511" alt="Image" src="https://github.com/user-attachments/assets/0b2659f7-3107-4d3e-8783-b0fb67a725b1" />

I also verified nothing returned running `nm -D --defined-only /usr/lib/rstudio-server/bin/rsession | grep pcre`
