### ISSUE TITLE
Fails to build with Boost 1.69 (develop snapshot)

### ISSUE THREAD

**Issue by jbeich** [rstudio/rstudio#3760]
After https://github.com/boostorg/boost/pull/189 build fails, see [error log](https://ptpb.pw/SWAe) (for rstudio 1.2.679) and [missing files](https://reviews.freebsd.org/differential/changeset/?ref=585402) (in boost 1.69)
```
CMake Error at /usr/local/share/cmake/Modules/FindBoost.cmake:2049 (message):
  Unable to find the requested Boost libraries.

  Boost version: 1.69.0

  Boost include path: /usr/local/include

  Could not find the following Boost libraries:

          boost_signals

  Some (but not all) of the required Boost libraries were found.  You may
  need to install these additional Boost libraries.  Alternatively, set
  BOOST_LIBRARYDIR to the directory containing Boost libraries or BOOST_ROOT
  to the location of Boost.
Call Stack (most recent call first):
  src/cpp/CMakeLists.txt:208 (find_package)
```
Note, Boost 1.69 is [scheduled](https://www.boost.org/development/) to be released on 2018-12-12.

**Comment by jbeich** [comment]
Duplicate of #2210?

**Comment by jbeich** [comment]
After boostorg/logic@23cd89d4c80f build also fails. See [error log](https://ptpb.pw/dz0m).
```c++
In file included from src/cpp/core/r_util/RSourceIndex.cpp:24:
In file included from src/cpp/core/include/core/r_util/RSourceIndex.hpp:36:
src/cpp/core/include/core/r_util/RFunctionInformation.hpp:78:33: error:
      no viable conversion from returned value of type 'const boost::tribool' to function return type 'bool'
   bool isUsed() const { return isUsed_; }
                                ^~~~~~~
src/cpp/core/include/core/r_util/RFunctionInformation.hpp:80:47: error:
      no viable conversion from returned value of type 'const boost::tribool' to function return type 'bool'
   bool isMissingnessHandled() const { return isMissingnessHandled_; }
                                              ^~~~~~~~~~~~~~~~~~~~~
src/cpp/core/include/core/r_util/RFunctionInformation.hpp:133:14: error:
      no viable conversion from returned value of type 'boost::logic::tribool' to function return type 'bool'
      return isPrimitive_ == true;
             ^~~~~~~~~~~~~~~~~~~~
src/cpp/session/modules/SessionRParser.cpp:411:14: error: no viable conversion from returned value of type 'boost::tribool' to function return type 'bool'
      return fnInfo.performsNse();
             ^~~~~~~~~~~~~~~~~~~~
```

**Comment by kevinushey** [comment]
I believe this should be fixed on master now -- @jbeich, if you're still seeing failures during compile please let us know.
