### ISSUE TITLE
error: 'SSL_R_SHORT_READ' was not declared in this scope

### ISSUE THREAD

**Issue by Mailaender** [rstudio/rstudio#1855]
When trying to compile current stable (version 1.1.383) or latest trunk (version 1.1.399) on @openSUSE Tumbleweed I receive the following error:

```
[   40s] In file included from /usr/include/openssl/engine.h:30:0,
[   40s]                  from /usr/include/boost/asio/ssl/detail/openssl_types.hpp:23,
[   40s]                  from /usr/include/boost/asio/ssl/context_base.hpp:19,
[   40s]                  from /usr/include/boost/asio/ssl/context.hpp:27,
[   40s]                  from /home/abuild/rpmbuild/BUILD/rstudio-1.1.399/src/cpp/core/include/core/http/BoostAsioSsl.hpp:24,
[   40s]                  from /home/abuild/rpmbuild/BUILD/rstudio-1.1.399/src/cpp/core/http/SocketProxy.cpp:22:
[   40s] /home/abuild/rpmbuild/BUILD/rstudio-1.1.399/src/cpp/core/http/SocketProxy.cpp: In function 'bool rstudio::core::http::{anonymous}::isSslShutdownError(const rstudio::core::Error&)':
[   40s] /home/abuild/rpmbuild/BUILD/rstudio-1.1.399/src/cpp/core/http/SocketProxy.cpp:152:60: error: 'SSL_R_SHORT_READ' was not declared in this scope
[   40s]            error.code().value() == ERR_PACK(ERR_LIB_SSL, 0, SSL_R_SHORT_READ);
[   40s]                                                             ^
[   40s] /home/abuild/rpmbuild/BUILD/rstudio-1.1.399/src/cpp/core/http/SocketProxy.cpp:152:60: note: suggested alternative: 'SSL_F_SSL_READ'
[   41s] make[2]: *** [src/cpp/core/CMakeFiles/rstudio-core.dir/build.make:1530: src/cpp/core/CMakeFiles/rstudio-core.dir/http/SocketProxy.cpp.o] Error 1
[   41s] make[2]: *** Waiting for unfinished jobs....
[   52s] make[2]: Leaving directory '/home/abuild/rpmbuild/BUILD/rstudio-1.1.399/build'
[   52s] make[1]: *** [CMakeFiles/Makefile2:206: src/cpp/core/CMakeFiles/rstudio-core.dir/all] Error 2
[   52s] make[1]: Leaving directory '/home/abuild/rpmbuild/BUILD/rstudio-1.1.399/build'
[   52s] make: *** [Makefile:155: all] Error 2
```

Boost version is 1.65.1 https://software.opensuse.org/package/boost

**Comment by JanMarvin** [comment]
@Mailaender For a patch and a discussion, why this patch was not included see: https://github.com/rstudio/rstudio/pull/1063

**Comment by jmcphers** [comment]
What version of OpenSSL do you have on your system? I think you may be attempting to compile with 1.1  (RStudio only compiles against 1.0).

**Comment by Mailaender** [comment]
> [    8s] cycle: libopenssl-devel -> libopenssl-1_1_0-devel
> [    8s]   breaking dependency libopenssl-devel -> libopenssl-1_1_0-devel

The patch is currently used for https://aur.archlinux.org/packages/rstudio-desktop and also helped for openSUSE Tumbleweed https://build.opensuse.org/request/show/557476 (finally got it to build!) Looks like both
* https://software.opensuse.org/package/libopenssl1_0_0
* https://software.opensuse.org/package/libopenssl1_1_0

exist, but version 1.1.0 is preferred.

**Comment by datamole** [comment]
@Mailaender: How did you get it compiled finally? (sorry, I don't really get it from the links you provide above)

Does the patch you mention enable you to compile against libopenssl1_1_0? I am asking because I cannot install libopenssl1_0_0-devel alongside libopenssl1_1_0 in tumbleweed and some major packages like pip have dependencies on ibopenssl1_1_0 so I can't switch back to version 1.0.

**Comment by datamole** [comment]
What about the suggestion made during compilation process:  
... src/cpp/core/http/SocketProxy.cpp:152:60: note: suggested alternative: ‘SSL_F_SSL_READ’

Perhaps it would be all that would have to be done for migrating rstudio to libopenssl1_1_0?

**Comment by Mailaender** [comment]
We used the following patch e8c9a7783f3ff44dea2e2464b4bf2904325c72cd for openSUSE Tumblweed with libopenssl1_1_0.

**Comment by kevinushey** [comment]
What about guarding the usage of `SSL_R_SHORT_READ` based on whether it's defined or not? E.g. I think a patch of the form:

```
#ifdef SSL_R_SHORT_READ
<code handling short read error>
#endif
```

would ensure that RStudio could compile cleanly against both OpenSSL 1.0.0 and 1.1.0.

**Comment by Mailaender** [comment]
Sounds like an elegant plan and your https://github.com/rstudio/rstudio/pull/1894 was already merged.
