### ISSUE TITLE
install.packages(pkgName, type = "source") when Rtools is not in C:/Rtools NOT working in RStudio 1.2.5033 BUT works in RGui

### ISSUE THREAD

**Issue by gwd666** [rstudio/rstudio#6566]
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.2.5033 
    OS Version      :  MS Windows 10 Enterprise - Version 10.0.17763 Build 17763
    R Version       :   R-3.5.3 

### Steps to reproduce the problem
Install R-3.5.3 in C:/Program Files/R/
Install RStudio 1.2.5033 in C:/Program Files/RStudio
Install Rtools35 in C:/Program Files/Rtools 

Modify C:/Program Files/R/R-3.5.3/i386/etc/Makeconf - line 19 to 
BINPREF ?= c:/PROGRA~1/Rtools/mingw_32/bin/

Modify C:/Program Files/R/R-3.5.3/x64/etc/Makeconf - line 19 to 
BINPREF ?= c:/PROGRA~1/Rtools/mingw_64/bin/

Add "C:\Program Files\Rtools\bin" to System PATH ENV variable 
also added "C:\PROGRA~1\Rtools\bin" to Users PATH ENV variable 
just to make sure that the spaces in "Program Files" do not make me trip. 

Finally defined a User specific library path: 
`>.libPath("L:/R/win-lib/3.5") `

### Describe the problem in detail

When running package installation of type = "source" in R-3.5.3 (32-bit) RGui eg: 

`> install.packages("e1071", type = "source") `
 this results in successfull installation - as you may notice by the number of German messages (and the sessionInfo) below I am running in a German Locale! 
```
Installiere Paket nach ‘L:/R/win-lib/3.5’
(da ‘lib’ nicht spezifiziert)
--- Bitte einen CRAN Spiegel für diese Sitzung auswählen ---
```
Here I selected the Austrian CRAN mirror - ie Vienna Economics University 
```

versuche URL 'https://cran.wu.ac.at/src/contrib/e1071_1.7-3.tar.gz'
Content type 'application/x-gzip' length 582517 bytes (568 KB)
downloaded 568 KB

* installing *source* package 'e1071' ...
** Paket 'e1071' erfolgreich entpackt und MD5 Summen überprüft

   **********************************************
   WARNING: this package has a configure script
         It probably needs manual configuration
   **********************************************


** libs

*** arch - i386
c:/PROGRA~1/Rtools/mingw_32/bin/gcc  -I"C:/PROGRA~1/R/R-35~1.3/include" -DNDEBUG          -O3 -Wall  -std=gnu99 -mtune=core2 -c Rsvm.c -o Rsvm.o
c:/PROGRA~1/Rtools/mingw_32/bin/gcc  -I"C:/PROGRA~1/R/R-35~1.3/include" -DNDEBUG 
.... 
....
c:/PROGRA~1/Rtools/mingw_32/bin/g++ -shared -s -static-libgcc -o e1071.dll tmp.def Rsvm.o cmeans.o cshell.o floyd.o init.o svm.o -LC:/PROGRA~1/R/R-35~1.3/bin/i386 -lR
installing to L:/R/win-lib/3.5/e1071/libs/i386

*** arch - x64
...
...
"C:/PROGRA~1/R/R-35~1.3/include" -DNDEBUG          -O2 -Wall  -mtune=core2 -c svm.cpp -o svm.o
c:/PROGRA~1/Rtools/mingw_64/bin/g++ -shared -s -static-libgcc -o e1071.dll tmp.def Rsvm.o cmeans.o cshell.o floyd.o init.o svm.o -LC:/PROGRA~1/R/R-35~1.3/bin/x64 -lR
installing to L:/R/win-lib/3.5/e1071/libs/x64
** R
** inst
** byte-compile and prepare package for lazy loading
** help
*** installing help indices
  converting help for package 'e1071'
    finding HTML links ... fertig
    Discrete                                html 
...
... 
    tune.wrapper                            html  
    write.svm                               html  
** building package indices
** installing vignettes
** testing if installed package can be loaded
*** arch - i386
*** arch - x64
* DONE (e1071)
In R CMD INSTALL

Die heruntergeladenen Quellpakete sind in 
        ‘C:\Users\UserName\AppData\Local\Temp\RtmpgjEoWW\downloaded_packages’

```
Respective RGui 3.5.3 sessionInfo() 

```
> sessionInfo()
R version 3.5.3 (2019-03-11)
Platform: i386-w64-mingw32/i386 (32-bit)
Running under: Windows 10 x64 (build 17763)

Matrix products: default

locale:
[1] LC_COLLATE=German_Austria.1252  LC_CTYPE=German_Austria.1252    LC_MONETARY=German_Austria.1252
[4] LC_NUMERIC=C                    LC_TIME=German_Austria.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
[1] compiler_3.5.3 tools_3.5.3  
```
same procedure in RStudio has this result:   

```
> install.packages("e1071", type = "source")
Installing package into ‘L:/R/win-lib/3.5’
(as ‘lib’ is unspecified)
versuche URL 'https://cran.wu.ac.at/src/contrib/e1071_1.7-3.tar.gz'
Content type 'application/x-gzip' length 582517 bytes (568 KB)
downloaded 568 KB

"\\p1at.s-group.cc\0702\USERS\UserName\Daten"
CMD.EXE wurde mit dem oben angegebenen Pfad als aktuellem Verzeichnis gestartet.
UNC-Pfade werden nicht untersttzt.
Stattdessen wird das Windows-Verzeichnis als aktuelles Verzeichnis gesetzt.
```
### **The above text means (in English):**  
```
"\\p1at.s-group.cc\0702\USERS\UserName\Daten"
CMD.EXE was started with the above path as the current directory.  
UNC-Paths are not supported. 
Instead the WINDOWS directory will be used as the current directory. 

```
then the following messages are thrown 
```
* installing *source* package 'e1071' ...
** Paket 'e1071' erfolgreich entpackt und MD5 Summen überprüft (means in English 
successfully unpacked and MD5 sums checked) 

   **********************************************
   WARNING: this package has a configure script
         It probably needs manual configuration
   **********************************************


** libs

*** arch - i386
C:/Program Files/Rtools/mingw_32/bin/gcc  -I"C:/PROGRA~1/R/R-35~1.3/include" -DNDEBUG          -O3 -Wall  -std=gnu99 -mtune=core2 -c Rsvm.c -o Rsvm.o
sh: C:/Program: No such file or directory
make: *** [C:/PROGRA~1/R/R-35~1.3/etc/i386/Makeconf:208: Rsvm.o] Error 127
ERROR: compilation failed for package 'e1071'
* removing 'L:/R/win-lib/3.5/e1071'
* restoring previous 'L:/R/win-lib/3.5/e1071'
In R CMD INSTALL
Warning in install.packages :
  installation of package ‘e1071’ had non-zero exit status

The downloaded source packages are in
	‘C:\Users\UserName\AppData\Local\Temp\RtmpYVDhtV\downloaded_packages’
```

### Describe the behavior you expected
Successfull installation of the package from type = "source" in RStudio just like in RGui 3.5.3 (32-bit) 

What makes me curious is why R Gui install.packages(type = "source") does not bother about the UNC paths since it was made clear that the installation directory is on a well behaved non-UNC path drive letter. But RStudio somehow pulls that message and the "sh: C:/Program: No such file or directory" ERROR out of its hat, which based on my experience happens if the BINPREF is not defined correctly - but here imho badly defined BINPREF is not the case?  

One final remark/comment - ouput of 

```
> Sys.which("sh")
                                 sh 
"C:\\PROGRA~1\\Rtools\\bin\\sh.exe" 
```
and I might also add that this behavior does not occur with RStudio 1.1.463 on my machine. 
Could it be some registry issues? Since I do not have admin privileges I cannot check the Regsitry, if something went belly up there when upgrading the RStudio version from 1.1.463 to 1.2.5033! 

I might also add that the current working solution for this problem is installing Rtools under C:\Rtools, but since this is not an option for the general problem, I am looking for a way to tell RStudio where to find Rtools in non-default install paths?! 

- [x ] I have read the guide to submitting good bug reports at https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports . 
- [x ] I have installed the latest version of RStudio and confirmed that the issue still persists.
- [x ] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by gwd666** [comment]
I have noticed an interesting line of code in RStudio/R/modules/ModuleTools.R (RStudio 1.1.463) 

```
.rs.addFunction("isRtoolsOnPath", function()
{
   return (nzchar(Sys.which("ls.exe")) && nzchar(Sys.which("gcc.exe")))
})
```
The function has been modified quite a bit, this is the equivalent function in RStudio 1.2.5033 

```
.rs.addFunction("isRtoolsOnPath", function()
{
   # ensure that the Rtools utility 'bin' directory is on the PATH
   # (this is just a heuristic but works okay in general)
   if (!nzchar(Sys.which("ls.exe")))
      return(FALSE)
   
   # for newer versions of R, ensure that BINPREF is set
   # (since BINPREF may be going away in R 4.0.0 we don't require its
   # existence here)
   rv <- getRversion()
   if (rv >= "3.3.0" && rv < "4.0.0")
   {
      if (is.na(Sys.getenv("BINPREF", unset = NA)))
         return(FALSE)
   }
   
   # for older versions of R (with the old toolchain) check for 'gcc.exe'
   # on the PATH (assuming the old, multilib-variant of gcc)
   if (rv < "3.3.0")
   {
      if (!nzchar(Sys.which("gcc.exe")))
         return(FALSE)
   }
   
   # survived all checks; return TRUE
   TRUE
})
```     
IMHO this somehow breaks on the BINPREF although it is set in both (i386 and x64) Makeconf files.

**Comment by gwd666** [comment]
Another interesting fact 
Modified my .Rprofile in the following way 
`Sys.setenv(BINPREF = paste0('c:/PROGRA~1/Rtools/mingw_', ifelse(R.version$arch == 'i386', 32, 64), "/"))` 

This leads to slightly modified error 

```
** libs

*** arch - i386
c:/PROGRA~1/Rtools/mingw_32/gcc  -I"C:/PROGRA~1/R/R-35~1.3/include" -DNDEBUG          -O3 -Wall  -std=gnu99 -mtune=core2 -c Rsvm.c -o Rsvm.o
sh: c:/PROGRA~1/Rtools/mingw_32/gcc: No such file or directory
make: *** [C:/PROGRA~1/R/R-35~1.3/etc/i386/Makeconf:208: Rsvm.o] Error 127
ERROR: compilation failed for package 'e1071'
* removing 'L:/R/win-lib/3.5/e1071'
* restoring previous 'L:/R/win-lib/3.5/e1071'
In R CMD INSTALL
Warning in install.packages :
  installation of package ‘e1071’ had non-zero exit status

``` 
Which is definitely present 
![image](https://user-images.githubusercontent.com/57595487/78161185-5b353300-7445-11ea-9d3d-f57cfd320e7c.png)

**Comment by kevinushey** [comment]
> c:/PROGRA~1/Rtools/mingw_32/gcc

This should be `c:/PROGRA~1/Rtools/mingw_32/bin/gcc`; the `bin` is missing.

FWIW we more commonly see:

```
BINPREF = C:/path/to/Rtools/mingw_$(WIN)/bin/
```

That is, `$(WIN)` makes it possible to select the 32bit versus the 64bit toolchain.

**Comment by gwd666** [comment]
> > c:/PROGRA~1/Rtools/mingw_32/gcc
> 
> This should be `c:/PROGRA~1/Rtools/mingw_32/bin/gcc`; the `bin` is missing.
> 
> FWIW we more commonly see:
> 
> ```
> BINPREF = C:/path/to/Rtools/mingw_$(WIN)/bin/
> ```
> 
> That is, `$(WIN)` makes it possible to select the 32bit versus the 64bit toolchain.

Yeah will fix that - BUT THIS WAS AN UGLY HACK I DID in my .Rprofile SINCE the Makeconf file does not seem to get read correctly (if you check above I mentioned the correct modification as "Modify C:/Program Files/R/R-3.5.3/x64/etc/Makeconf - line 19 to
BINPREF ?= c:/PROGRA~1/Rtools/mingw_64/bin/"       

I also managed at least on my first test machine to fix the bug by commenting out this part in ModuleTools.R

```
#if (rv >= "3.3.0" && rv < "4.0.0")
#  {
#     if (is.na(Sys.getenv("BINPREF", unset = NA)))
#         return(FALSE)
#   } 

```
Probably hacking the BINPREF env var in .Rprofile is also a potential workaround - just think that there is some flaw in that BINPREF if loop in ModuleTools.R as well. 

Thanks for the swift reaction - (still) big fan of RStudio Desktop!

**Comment by mirh** [comment]
ModuleTools.R didn't see much change since this issue was opened, but I just tested 1.4.1103 and Rtools40 installed in program files and it worked (with `install.packages("crayon", type = "source")` at least)

Idk if it couldn't be due to the new MSYS2 environment, the RTOOLS40_HOME variable or whatnot.

**Comment by mirh** [comment]
Ok, so, I'm dumb. Crayon isn't a native code package, so no shit its source always installs cleanly. 
Then, yes, I can report eventually this got solved with RStudio 1.3, but only because it was the first version to [support](https://github.com/rstudio/rstudio/pull/6673) R/Rtools 4.0. 
But this wasn't a RStudio bug, or about "non-default paths", only spaces (which R 3.6 and/or Rtools 3.5 could [never](https://stackoverflow.com/a/72634375/5994170) truly bear).

I couldn't really reproduce version 1.1 behaving differently from 1.2, but RGui was instead working because of all the trouble OP went to add short names to PATH. 
On the other hand RStudio *also* employs the directions in `HKLM\SOFTWARE\WOW6432Node\R-core\Rtools\3.5` to determine the toolset location, and that was picking up the tragic "Program Files" snippet (which you notice is busted in the last console log).
