### ISSUE TITLE
[regression] error: no matching constructor for initialization of 'boost::posix_time::milliseconds'

### ISSUE THREAD

**Issue by yurivict** [rstudio/rstudio#2867]
Version 1.2.637 fails to build on FreeBSD 11.1:
```
/usr/ports/devel/RStudio/work/rstudio-1.2.637/src/cpp/core/ExponentialBackoff.cpp:71:36: error: no matching constructor for initialization of 'boost::posix_time::milliseconds' (aka 'subsecond_duration<boost::posix_time::time_duration, 1000>')
   boost::posix_time::milliseconds nextWait(initialWait_.total_milliseconds() * std::pow(2, totalNumTries_));
                                   ^        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/usr/local/include/boost/date_time/time_duration.hpp:270:30: note: candidate constructor (the implicit copy constructor) not viable: no known conversion from 'double' to 'const boost::date_time::subsecond_duration<boost::posix_time::time_duration, 1000>' for 1st argument
  class BOOST_SYMBOL_VISIBLE subsecond_duration : public base_duration
                             ^
/usr/local/include/boost/date_time/time_duration.hpp:270:30: note: candidate constructor (the implicit move constructor) not viable: no known conversion from 'double' to 'boost::date_time::subsecond_duration<boost::posix_time::time_duration, 1000>' for 1st argument
/usr/local/include/boost/date_time/time_duration.hpp:286:59: note: candidate template ignored: disabled by 'enable_if' [with T = double]
                                typename boost::enable_if<boost::is_integral<T>, void>::type* = 0) :
                                                          ^
```

boost-libs-1.67.0_1

**Comment by kevinushey** [comment]
Thanks for the bug report. This appears to be caused by the upgrade to Boost 1.67.0 -- I'll take a look.

**Comment by kevinushey** [comment]
This commit should fix the issue:

https://github.com/rstudio/rstudio/commit/85896f38b7d25661dd29f76b2bbf1b64d5e34fa4

Are you able to include that as a patch in the version of RStudio you build on FreeBSD?

**Comment by yurivict** [comment]
I've included the patch, thanks!
