### ISSUE TITLE
Fails to build with boost 1.70: error: no member named 'get_io_service' in 'boost::asio::ip::basic_resolver<boost::asio::ip::tcp, boost::asio::executor>'

### ISSUE THREAD

**Issue by yurivict** [rstudio/rstudio#4636]
See the downstream bug report here: https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=236603

**Comment by kevinushey** [comment]
Looks like `get_io_service()` was indeed removed in Boost 1.70: https://www.boost.org/doc/libs/1_70_0/doc/html/boost_asio/history.html

Looks like `.get_executor().context()` should be used instead, and most usages of `io_service` should become `io_context`.

**Comment by ivr588** [comment]
Is this likely to be fixed in the near future?

**Comment by yurivict** [comment]
I would like to know too, because the FreeBSD port is marked BROKEN because of this, and I can't even use ```RStudio``` at the moment myself.

**Comment by yurivict** [comment]
@gtritchie Do you know is there a particular reason why boost compatibility doesn't get fixed?

**Comment by jmcphers** [comment]
We don't typically upgrade on every single new Boost release because it's relatively expensive to do so. It takes time to retrofit any call site affected by deprecation, to test for regressions introduced by breaking behavioral changes (of which there are also typically several), etc. PRs are of course welcome!

Is there a reason you can't compile RStudio against the Boost 1.69 libraries (with which it is compatible)?

**Comment by yurivict** [comment]
> Is there a reason you can't compile RStudio against the Boost 1.69 libraries (with which it is compatible)?

The FreeBSD boost port has been updated to 1.70, and RStudio is now marked BROKEN because it doesn't build. I can't just build it with boost-1.69 because it isn't available in ports any more.

**Comment by yurivict** [comment]
> Is there a reason you can't compile RStudio against the Boost 1.69 libraries (with which it is compatible)?

@jmcphers The reason is that the boost package was upgraded to 1.70.0 and 1.69 isn't available any more.

**Comment by a17r** [comment]
Same for Gentoo. It's not as if adapting to changes in 1.70 can somehow be skipped by waiting.

**Comment by yurivict** [comment]
Yeah, ```boost-1.70``` isn't going to go away any time, IMO.

**Comment by MasterCATZ** [comment]
ugh another application broken because on 1.70 , please update support

**Comment by kevinushey** [comment]
This should be fixed for RStudio v1.3 (and v1.4) already. If you're still seeing compilation errors, please file a separate issue with the exact errors you're seeing. Thanks!

**Comment by yurivict** [comment]
The current ```v1.2.5033``` version builds fine with ```boost-libs-1.72.0``` with clang8.
