### PR TITLE
fix EnvironmentScope previous-value capture on windows

### PR DESCRIPTION
**Pull request by kevinushey**
Fixes the `ide-os-windows/main` build break introduced by #18520 (first red run: build 3710). The new core gtest `EnvironmentTest.EnvironmentScopeRestoresPreviousValue` fails deterministically on Windows:

```
src\cpp\core\system\EnvironmentTests.cpp(79): error: Expected equality of these values:
  "original"
  getenv("RSTUDIO_ENV_SCOPE_TEST")
    Which is: ""
```

### Root cause

`EnvironmentScope` captured the previous value with raw `::getenv`, but `core::system::setenv` writes through `SetEnvironmentVariableW`. On Windows those are two different stores: `::getenv` reads the CRT's `_environ` snapshot taken at process start, which `SetEnvironmentVariable` never updates. Any variable set via `core::system::setenv` was invisible to the scope, so its destructor took the "was unset" path and deleted the variable instead of restoring it. On POSIX both calls hit the same libc `environ`, which is why the test was green locally and on the other platforms.

### Fix

Add an existence-preserving accessor to `core::system`:

```cpp
bool getenv(const std::string& name, std::string* pValue);
```

- POSIX: `::getenv` under the environment lock, `nullptr` -> `false`.
- Windows: `GetEnvironmentVariableW` under the lock (the same store the setters write), with `ERROR_ENVVAR_NOT_FOUND` distinguishing unset.

`EnvironmentScope` now captures the previous value through this overload, keeping the unset vs set-but-empty distinction #18520 introduced (on POSIX; that distinction does not exist on Windows, where setting a variable to the empty string deletes it). This also removes the last raw `::getenv` from the public header, along with the `stdlib.h` and `EnvironmentLock.hpp` includes it needed -- every remaining `EnvironmentLock` user includes that header directly.

The Windows brokenness predates #18520 but never had production impact: the only non-test `EnvironmentScope` user is Apple-only (`SourceIndex.cpp`), and `XdgTests.cpp` is compiled out on Windows, so the new test was the first code to exercise `EnvironmentScope` there.

### Tests

- New gtest `EnvironmentTest.GetenvOverloadDistinguishesUnset` covers unset/set round-trips through `setenv` (which on Windows exercises exactly the CRT-vs-process-block mismatch) plus the POSIX-only set-but-empty case.
- macOS: full core suite green (491 passed / 8 skipped), full backend build clean.
- Windows: not verifiable from this machine -- `Win32Environment.cpp` needs the Windows CI build; the failing test should flip to green on the next `ide-os-windows` run.

### CODE REVIEW

**Comment by gtritchie** [comment]
## Code review findings

Non-blocking. The fix itself looks right: reading through `GetEnvironmentVariableW` under the same lock the setters use is the correct store, the `result > nSize` truncation test is right (a required size equal to the buffer size would have fit and returned a success count instead), and dropping the header's `EnvironmentLock.hpp` / `stdlib.h` includes is safe — the four remaining `EnvironmentLock` users all include it directly.

One suggestion:

1. `src/cpp/core/system/Win32Environment.cpp:92` — the new two-arg `getenv` is a near-verbatim copy of `detail::getenv` (`src/cpp/shared_core/system/Win32User.cpp:137`): same 256-char buffer, same resize retry, same failure handling. The copies have already diverged on how they widen the name — the new one uses `string_utils::utf8ToWide`, `detail::getenv` widens byte-by-byte with `std::wstring nameWide(name.begin(), name.end())`. For a name with non-ASCII characters (`"VÄR"`, UTF-8 `56 C3 84 52`) that yields `L"VÃR"` vs. `L"VÄR"`, so the two overloads look up different variables. Having the one-arg `getenv` delegate to the new two-arg one removes the duplication and the divergence together, since the byte-wise widening is the incorrect copy.

   Minor, in the same function: on the resize-retry path a failed second call returns `false`, which callers read as "variable unset" rather than "read failed" — an `EnvironmentScope` would then `unsetenv` a variable it meant to restore. The window requires the variable to be deleted between the two calls by something outside the environment lock, so this is theoretical; worth a log rather than a silent `false`.

**Comment by kevinushey** [comment]
Both applied in c5df09e:

1. The one-arg `getenv` now delegates to the two-arg overload, so core no longer goes through `detail::getenv`'s byte-wise widening. The shared_core copy stays as-is -- shared_core can't depend on core, and its remaining callers only pass ASCII names (`HOMEDRIVE`/`HOMEPATH`/`R_USER`).
2. The failed retry now logs the variable name via `WLOGF` before reporting unset.

Writing a round-trip test for the widening divergence turned up one more instance of the same class: `unsetenv` was calling the ANSI `SetEnvironmentVariable` with UTF-8 bytes, so under a non-UTF-8 ANSI code page it would delete the wrong variable for a non-ASCII name. Now goes through `SetEnvironmentVariableW` like the other accessors. The new `AccessorsAgreeOnNonAsciiNames` gtest covers all three accessors and fails on the old code on Windows.
